### ISSUE TITLE
Attachment files overwritten for identical screenshots with rspec-retry

### ISSUE THREAD

**Issue by jabbrwcky** [allure-framework/allure-ruby-commons#22]
Hi,

when running Allure reports with rspec retry Tests may fail with identical screenshots causing added attachments to overwrite the previously attached file.

This is caused by using SHA256 for determining a file name for an attachment. It would be safer to use a different approach for generating unique attachment filenames like UUID.

I'll add a PR with the required changes.

**Comment by baev** [comment]
@jabbrwcky that is implemented like this by design to reduce report size. Each test case will have it's own attachment that links to the same file. The only problem is that sha256 requires more CPU time

**Comment by baev** [comment]
(Here)[https://github.com/allure-framework/allure-core/wiki/Creating-Allure-Adapter#output-file-conventions] you can find more information about format of results files.

**Comment by jabbrwcky** [comment]
@baev Fair point. 

It might run in collisions though if you run tests concurrently. 

Maybe it would be an idea to skip the copying of the file if the destination attachment file already exists.

**Comment by baev** [comment]
> It might run in collisions though if you run tests concurrently.
> 
> Maybe it would be an idea to skip the copying of the file if the destination attachment file already exists.

The idea is that adaptor will handle situations like this. I guess there is no reason to override attachment file if it already exists. And we should handle concurrent situation as well (as example you can see [java-api](https://github.com/allure-framework/allure-core/blob/master/allure-java-adaptor-api/src/main/java/ru/yandex/qatools/allure/utils/AllureResultsUtils.java#L271-L277)).

**Comment by smecsia** [comment]
>  (as example you can see java-api).
That would require cross-process locking, because ruby concurrent runners usually use multiple processes rather than multiple threads.

**Comment by baev** [comment]
allure ruby commons module was rewritten to support Allure 2 features. New repository located here https://github.com/allure-framework/allure-ruby
