### ISSUE TITLE
Allure Core 2.0 Support

### ISSUE THREAD

**Issue by tk8817** [allure-framework/allure-ruby-commons#25]
Hey folks,

Figured I would start the conversation about getting ready for `Allure Core 2.0`. Is there anyone on the yandex team who is gearing up to port the ruby adaptor? If not, please let us know how the community can step up and help.

**Comment by baev** [comment]
Allure 2 fully supports old adaptors. We are going to refactor all the adaptors after final release of Allure 2.0 to support new features.

**Comment by tk8817** [comment]
@baev fully aware of the backward compatibility :) was hoping to get involved with having the ruby adapters updates before the final release as I am maintaining the allure-cucumber repo these days.

**Comment by baev** [comment]
Sounds good to me

**Comment by WoolenWang** [comment]
is that support of Allure Core 2.0 report is begin to go? We use allure ruby report, and we are waiting for your update~ thanks

**Comment by baev** [comment]
done https://github.com/allure-framework/allure-ruby
