### ISSUE TITLE
Inspec/ServerSpec integration

### ISSUE THREAD

**Issue by etki** [allure-framework/allure-ruby-commons#28]
Couple of Ruby tools, [Inspec](https://www.inspec.io/) and [ServerSpec](http://serverspec.org/), have occupied a very interesting niche: infrastructure testing that validates target machine for being compliant to set of rules. While both of them are based on RSpec, and generally RSpec adapter should fit in somehow, they are often used under not so common conditions ([Test Kitchen](http://kitchen.ci/) that allows only declarative configuration or simply run by people that are not familiar with Ruby enough), what restricts people from using Allure reports - and they would come *very* handy since  security-concerning Inspec check may consist of thousands of assertions, and usually those tools are used against of fleet of machines. That would be terribly lovely to add a cherry on top of infrastructure automation stack Chef guys has made, because currently i can validate may configuration against all possible distros i can imagine, but it's quite difficult to find who exactly has failed (especially if tests are run concurrently, which is typical for test Test Kitchen with tens of target distros).

So, this issue suggests

- Finding a way to add direct support for Inspec/ServerSpec, using RSpec formatter, if possible
- Implementing it
- Possibly adding some changes directly in Inspec and/or ServerSpec (since, by default, declarative-only Inspec configuration may only choose one of built-in formatters)

There is a possibility that i'll do it one day myself, but past experience tells me that's not what i can be sure about.
Feel free to ask me about details of Inspec/Test Kitchen usage, if you need any.

**Comment by tk8817** [comment]
@etki - thanks for the post. There are no changes required on the Allure side to support this. 

If Inspec/ServerSpec are not letting you directly set an RSpec configure blcok, there are still a couple ways to try get Allure loaded. First, try add a `.rspec` file in the root of your Inspec / ServerSpec project and put the formatter loading code in there. 

When it comes to allure specific functions though (logging metadata from `step`s which live inside `it`s) that is a change which comes from within your specs and as long as ServerSpec/InSpec are reading spec files, you should be fine.

Best,
