### ISSUE TITLE
Add time argument to start_step and stop_step methods

### ISSUE THREAD

**Issue by 9ikhan** [allure-framework/allure-ruby-commons#5]
I have few steps in cucumber-adaptor which I can't execute in realtime so I would want to be able to pass   time as  argument to `start_step` and `stop_step` methods.

Making it optional won't break anything in adaptors

``` ruby
    def start_step(suite, test, step, time  = Time.now)
        MUTEX.synchronize do
          puts "Starting step #{suite}.#{test}.#{step}"
          self.suites[suite][:tests][test][:steps][step] = {
              :title => step,
              :start => timestamp(time),
              :attachments => []
          }
        end
    end

   def stop_step(suite, test, step, status = :passed, time = Time.now)
        MUTEX.synchronize do
          puts "Stopping step #{suite}.#{test}.#{step}"
          self.suites[suite][:tests][test][:steps][step][:stop] = timestamp(time)
          self.suites[suite][:tests][test][:steps][step][:status] = status
        end
   end
```

@smecsia - If this looks ok to you then I will send a pull request.

**Comment by smecsia** [comment]
Why don't we make it an options hash, not the ordinary param? Like so: 
```ruby
def stop_step(suite, test, step, status = :passed, opts = {:time => Time.now})
```
Lots of params looks ugly, so I would do the same with the `status` param, but for now we can keep it not to break anything. I think this form of call to `stop_step` would be a bit nicer:
```ruby
builder.stop_step(suite, test, step, :passed, time : Time.now)
```
Later we'll migrate to ruby >= 2 and replace last two params with keyword arguments like so:
```ruby
def stop_step(suite, test, step, status: :passed, time: Time.now)
```

**Comment by baev** [comment]
allure ruby commons module was rewritten to support Allure 2 features. New repository located here https://github.com/allure-framework/allure-ruby
